version: '2'

services:
      
  dotnet-aspnetcore:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/app
      - nuget:/root/.nuget
    ports:
     - "5000:5000"

volumes:
  nuget: